frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

film_show:
    path:     /film/show/{id}
    defaults: { _controller: FrontendBundle:Default:show }

film_new:
    path:     /film/new
    defaults: { _controller: FrontendBundle:Default:newFilm }
